### ISSUE TITLE
[Bug] SteamVR Overlay completely broken.

### ISSUE THREAD

**Issue by ZacGames** [vrcx-team/VRCX#668] opened 2023-10-13 08:51 UTC
**Describe the bug**
SteamVR overlay is no longer working. It seems to be bugging out entirely. XSOverlay notifications still work.

**To Reproduce**
Turn on SteamVR overlay (wrist overlay optional but also broken)
Watch it break.

**Expected behavior**
Should let me access the overlay, both in the steam menu and on the wrist.

**Screenshots**
I have a video.
https://github.com/vrcx-team/VRCX/assets/120276008/63556e69-12f7-415f-bd49-858f11ed1e28

**What version you are running**
Latest Nightly version. Note that it's on the live version too.

Other notes: I have reinstalled twice, Restarting doesn't work. Changing to the beta of both SteamVR and the Steam client doesn't change anything about this. The only thing I haven't done is reinstall windows.

**Comment by ZacGames** [comment] 2023-10-13 08:56
okay i found the issue, i turned off the gpu fix setting and it stabilized.

**Comment by Natsumi-sama** [comment] 2023-10-13 08:57
~~On the latest nightly I've recently added logging for when the overlay fails to start in `%AppData%\VRCX\logs` but most of the time when the overlay fails to start it's due to multiple GPUs and the overlay using the wrong one, try change the `SteamVR Overlay GPU Fix` option in Settings -> Advanced~~

ah never mind then yup.

**Comment by ZacGames** [comment] 2023-10-13 08:59
> On the latest nightly I've recently added logging for when the overlay fails to start in `%AppData%\VRCX\logs` 
i'll keep that in mind for future overlay issues, thank you.

**Comment by ZacGames** [comment] 2023-10-16 01:41
Okay, the issue is back. I checked the logs and it just says "RequestFailed"

**Comment by dark-swordsman** [comment] 2023-11-13 00:44
I can confirm the overlay has been broken for me as well. Is there anything I can provide?

**Comment by Natsumi-sama** [comment] 2023-11-13 00:50
> On the latest nightly I've recently added logging for when the overlay fails to start in `%AppData%\VRCX\logs` but most of the time when the overlay fails to start it's due to multiple GPUs and the overlay using the wrong one, try change the `SteamVR Overlay GPU Fix` option in Settings -> Advanced

Try this, also check your log file `C:\Program Files (x86)\Steam\Logs\vrclient_VRCX.txt`

**Comment by Myrkie** [comment] 2023-11-13 19:58
a recent potential fix has been pushed to the nightly branch from 11/13 could you try updating to that and see if it solves your issues. you can access this update from settings > VRCX Updater > Change build

**Closed** 2023-12-30 22:15 UTC
Labels: bug

**Comment by dark-swordsman** [comment] 2023-12-31 03:23
I just wanted to confirm that it is working for me now after one of the the latest updates.
