### ISSUE TITLE
[Bug] Avatar Image

### ISSUE THREAD

**Issue by Josh425** [vrcx-team/VRCX#602] opened 2023-07-17 11:28 UTC
When i Try To Change My Avatar Image On A Avatar It Gives Me Errors
![Screenshot 2023-07-17 122806](https://github.com/vrcx-team/VRCX/assets/108227072/bbf233d0-e47a-4e28-97af-1263872a68e0)
![Screenshot 2023-07-17 122757](https://github.com/vrcx-team/VRCX/assets/108227072/361c14a3-91ef-4030-97d9-351a4623c210)

**Comment by Myrkie** [comment] 2023-07-20 01:34
this is caused by a failed upload of a previous image, this can either be caused by the latter a failed previous upload, or if the avatar was ripped and re uploaded/stolen.

**Comment by Natsumi-sama** [comment] 2023-07-20 01:35
nah this one was a nighty bug, all fixed now though.

**Closed** 2023-07-29 20:15 UTC
Labels: bug, done
