### ISSUE TITLE
After 12/30 Update, VRCX Won't Launch

### ISSUE THREAD

**Issue by Alucard0504** [vrcx-team/VRCX#462] opened 2022-12-30 07:51 UTC
Something is preventing VRCX from running. If you launch it after opening, it closes immediately

**Comment by Natsumi-sama** [comment] 2022-12-30 07:53
Does it still crash if you downgrade to the previous release?

**Comment by Alucard0504** [comment] 2022-12-30 08:01
No. After re-installing the previous version, Everything works fine

**Comment by Natsumi-sama** [comment] 2022-12-30 08:58
Does installing/repairing this help? https://aka.ms/vs/17/release/vc_redist.x64.exe
Try re-download the setup.

**Comment by Alucard0504** [comment] 2022-12-30 20:36
That did not fix the issue.... still crashes if I install the update

**Comment by Natsumi-sama** [comment] 2022-12-30 20:39
One of my friends recently got this bug as well so I will remotely debug it with them later and report back with any findings.

**Comment by SloanGwaltney** [comment] 2022-12-31 08:17
I have the newest version on Windows 10 with no issues, but a friend has it on Windows 11 and has the issue described.

**Comment by Natsumi-sama** [comment] 2022-12-31 08:19
Hmm okay thanks for the info I'll give a Windows 11 VM a try.

**Comment by Natsumi-sama** [comment] 2022-12-31 08:37
Unfortunately I still can't reproduce the issue with Windows 11.

**Comment by Alucard0504** [comment] 2022-12-31 16:34
I am on windows 10 with the issue

**Comment by AvocadoVR** [comment] 2022-12-31 19:16
It may because of the anti-virus. When the update was released thats when I had issues and my anti-virus removed VRCX it may be termniating the process.

**Comment by Alucard0504** [comment] 2022-12-31 20:49
I dont have any third party anti-virus installed on my PC.... just windows defender. So that is not the issue either

**Comment by Natsumi-sama** [comment] 2022-12-31 21:07
My friend was kind enough to let me install Visual Studio on their computer I was able to find the new Cef version was causing the crash although I'm not sure as to why but I've downgraded to the last working version.
In short re-download the setup it should be fixed now.

**Closed** 2023-02-17 22:55 UTC
Labels: bug, done
