### ISSUE TITLE
[Bug]  I can't open vrcx.

### ISSUE THREAD

**Issue by ladyc0libri** [vrcx-team/VRCX#725] opened 2024-01-18 10:52 UTC
It is not working for me. I have already reinstalled it 2 times, but vrcx won't open..
I click on the icon and nothing happens. When i click again, it says VRCX is already open, but there s no vrcx windows.

I have downloaded latest version, still nothing has changed

**Comment by Myrkie** [comment] 2024-01-18 10:53
which version of vrcx are you running? 
Nightly or Stable?

**Comment by Myrkie** [comment] 2024-01-18 10:54
also if you haven't check the tray icon at the bottom of your taskbar and double click it.
![image](https://github.com/vrcx-team/VRCX/assets/20288698/1e090402-41b0-45f5-b33f-2aa2f30a0766)

**Comment by ladyc0libri** [comment] 2024-01-18 10:57
about version idk.. i just downloaded these 2 files, opened them, it said vrcx download is finished and thats it
![image](https://github.com/vrcx-team/VRCX/assets/157014916/ce9b80f0-ac23-4453-a2b9-60889d099703)

![image](https://github.com/vrcx-team/VRCX/assets/157014916/5a5cf19b-8e83-4125-8e56-a1f801ee3c48)

**Comment by ladyc0libri** [comment] 2024-01-18 10:58
everything was alright yesterday, today smth happenned

**Comment by Myrkie** [comment] 2024-01-18 11:00
> about version idk.. i just downloaded these 2 files, opened them, it said vrcx download is finished and thats it ![image](https://private-user-images.githubusercontent.com/157014916/297716164-ce9b80f0-ac23-4453-a2b9-60889d099703.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NzU3NzAsIm5iZiI6MTcwNTU3NTQ3MCwicGF0aCI6Ii8xNTcwMTQ5MTYvMjk3NzE2MTY0LWNlOWI4MGYwLWFjMjMtNDQ1My1hMmI5LTYwODg5ZDA5OTcwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxMDU3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTU4Njg3MzJjN2NhNDY5ZjdkMTg3MjhmOWYzNDZkNGU4OWMxZGJmOWU5MWM0ZmQ5NDAxMDQxMzNhZjU5YmZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HORx-17LWSsz-U33vIVQtuZf3ZbLeaYS--BrwsoFPpk)
> 
> ![image](https://private-user-images.githubusercontent.com/157014916/297716036-5a5cf19b-8e83-4125-8e56-a1f801ee3c48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NzU3NzAsIm5iZiI6MTcwNTU3NTQ3MCwicGF0aCI6Ii8xNTcwMTQ5MTYvMjk3NzE2MDM2LTVhNWNmMTliLThlODMtNDEyNS04ZTU2LWExZjgwMWVlM2M0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxMDU3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzcwMjIyOWQ4YTk5Y2Q5NTA2ZTVlMjY5YWFkYzAxODkwMzljOTIwNDdlZTM4NGMyOGZiNWIwMjIwODRiMGY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZncsKfHa4OMVDbzBC6Pv3R6asyYBpuO0ONUhWw8Ic-o)

you only need to download one of the files, the zip is portable installation while the exe is a installer version, try going to your vrcx installation directory and running vrcx manually, if it still says vrcx is already open open task manager (Ctrl + Shift + Esc) and navigate to the Details tab and manually close all instances of VRCX.exe and try again

![image](https://github.com/vrcx-team/VRCX/assets/20288698/b2df4a74-c0d6-4849-aae8-e6320f4cf425)

**Comment by ladyc0libri** [comment] 2024-01-18 11:13
I tried to do this, but it didnt open. I have noticed that when i click on vrcx it appears in the task manager, and after about 40 sec it disappears from there

**Comment by ladyc0libri** [comment] 2024-01-18 11:14
like it closes itself

**Comment by Myrkie** [comment] 2024-01-18 11:18
> like it closes itself

its possible that the upgrade to .net 8 in the latest release is missing the runtime, try installing the .net 8 desktop runtime from [Microsoft .net 8](https://dotnet.microsoft.com/en-us/download/dotnet/8.0) and restart your pc 

Direct link here

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.1-windows-x64-installer

**Comment by ladyc0libri** [comment] 2024-01-18 11:23
well.. i did everything you said and nothing changed:(
idk whats the problem..

**Comment by Myrkie** [comment] 2024-01-18 11:25
can you go to `%AppData%\..\Roaming\VRCX\logs` and post the latest log file? should be called `VRCX.log`

**Comment by ladyc0libri** [comment] 2024-01-18 11:48
![image](https://github.com/vrcx-team/VRCX/assets/157014916/aad5a579-7845-43da-b778-f4f38da1a2a5)
which one?

**Comment by Myrkie** [comment] 2024-01-18 11:51
the first one

**Comment by ladyc0libri** [comment] 2024-01-18 11:53
![image](https://github.com/vrcx-team/VRCX/assets/157014916/6ca89cfa-692c-46d5-865c-0d2f5fa75260)

**Comment by Myrkie** [comment] 2024-01-18 11:54
hmm interesting, vrcx is reporting no issues, not sure what the issue could be.

**Comment by ladyc0libri** [comment] 2024-01-18 11:56
:,(

**Comment by ladyc0libri** [comment] 2024-01-18 11:58
werfault apperars before vrcx closes in task manager

**Comment by Myrkie** [comment] 2024-01-18 11:59
> werfault apperars before vrcx closes in task manager

do you happen to have a crash dump from vrcx? these usually are located in `%AppData%\..\Local\CrashDumps`

**Comment by Myrkie** [comment] 2024-01-18 12:03
![image](https://github.com/vrcx-team/VRCX/assets/20288698/8fb63e51-f696-4f7e-afbc-d76aab6ada57)
can you check the direct path?

**Comment by ladyc0libri** [comment] 2024-01-18 12:04
![image](https://github.com/vrcx-team/VRCX/assets/157014916/296714ac-16a0-48ee-9f79-f4b34a88806a)
yep

**Comment by Myrkie** [comment] 2024-01-18 12:06
can you upload the latest version, sort by date and send the most recently generated .dmp file.

**Comment by ladyc0libri** [comment] 2024-01-18 12:07
![image](https://github.com/vrcx-team/VRCX/assets/157014916/c76b2f9a-d84b-4f3b-8438-7a837ef74fe2)
this?

**Comment by Myrkie** [comment] 2024-01-18 12:08
yes vrcx.exe.15152

**Comment by ladyc0libri** [comment] 2024-01-18 12:10
[VRCX.exe.15152.dmp](https://github.com/vrcx-team/VRCX/files/13976372/VRCX.exe.15152.dmp)

**Comment by Myrkie** [comment] 2024-01-18 12:19
try rebooting your computer and running windows update, if the issue persists try running these commands in an administrative windows command prompt or windows terminal 

![image](https://github.com/vrcx-team/VRCX/assets/20288698/5cabe508-4110-4766-923f-74cbd5c2a6cd)


`regsvr32.exe /u ntdll.dll`
`regsvr32.exe ntdll.dll`

then reboot again and attempt to start vrcx

**Comment by Myrkie** [comment] 2024-01-18 12:20
if neither of the suggestions work its time for you to run system file checker, open command prompt as adminstrator as seen by the picture above and run

`sfc /scannow`

**Comment by Myrkie** [comment] 2024-01-18 12:30
For a wrap up for this, the dump indicates that your windows system integrity is damaged and the reported fault is in ntdll.dll which is a core windows system component if neither of the provided fixes work then you will have to reinstall windows or attempt a higher level repair such as using windows DISM

**Comment by ladyc0libri** [comment] 2024-01-18 12:54
sounds bad:( thank you so much anyways..

**Comment by kaylathedev** [comment] 2024-01-18 16:59
I have the same issue as @ladyc0libri . When I go to open VRCX from the system tray, the window does not appear. Attempting to re-open will say that VRCX is already running. I forced closed the process from task manager. I even checked my system with `/sfc scannow`. It reported corrupt files but fixed them. My VRCX log looks the same as theirs.

I opened the devtools window by right clicking the system tray icon, and checked the screen coordinates in the console. It seems to be off the screen? The y coordinate seems to be putting the window below the taskbar.

![vrcx problem 2](https://github.com/vrcx-team/VRCX/assets/5334284/9a7a96db-101d-478c-bae4-ed6e2220302a)

Inside the `%appdata%/VRCX/VRCX.json` file contains an entry as such, `"VRCX_LocationY": "1066"`. If I change y coordinate from 1066 to 0, it temporally fixes the bug.

I'm thinking the program should, when starting up, check if the initial coordinates is going to put it off screen. If true, then reset the coordinates to 0.

Windows 10 Pro, build 19045.3930
VRCX 2023.12.24

[VRCX.log](https://github.com/vrcx-team/VRCX/files/13979420/VRCX.log)

**Comment by Myrkie** [comment] 2024-01-18 17:13
> I have the same issue as @ladyc0libri . When I go to open VRCX from the system tray, the window does not appear. Attempting to re-open will say that VRCX is already running. I forced closed the process from task manager. I even checked my system with `/sfc scannow`. It reported corrupt files but fixed them. My VRCX log looks the same as theirs.
> 
> I opened the devtools window by right clicking the system tray icon, and checked the screen coordinates in the console. It seems to be off the screen? The y coordinate seems to be putting the window below the taskbar.
> 
> ![vrcx problem 2](https://private-user-images.githubusercontent.com/5334284/297820068-9a7a96db-101d-478c-bae4-ed6e2220302a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTgwNjEsIm5iZiI6MTcwNTU5Nzc2MSwicGF0aCI6Ii81MzM0Mjg0LzI5NzgyMDA2OC05YTdhOTZkYi0xMDFkLTQ3OGMtYmFlNC1lZDZlMjIyMDMwMmEuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMTcwOTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTcwN2Q3MTEwNWI5Y2MyMzhkZTViNGU5ZTJlNjA1YmNkMjkxNTE2NTAxN2RlYjIxYmRhZTcwMjhhODFlZjBiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vaOoxsxAb6xyvmxZpCucwwj8QshaR1ZXfkRm6MfS0ak)
> 
> Inside the `%appdata%/VRCX/VRCX.json` file contains an entry as such, `"VRCX_LocationY": "1066"`. If I change y coordinate from 1066 to 0, it temporally fixes the bug.
> 
> I'm thinking the program should, when starting up, check if the initial coordinates is going to put it off screen. If true, then reset the coordinates to 0.
> 
> Windows 10 Pro, build 19045.3930 VRCX 2023.12.24
> 
> [VRCX.log](https://github.com/vrcx-team/VRCX/files/13979420/VRCX.log)

this is a unrelated issue, your vrcx remains working as expected, in [ladyc0libri](https://github.com/ladyc0libri) case their vrcx copy completely crashes because of a integrity violation within windows, as for your issue with vrcx this can be fixed by holding windows key + arrow up after clicking on vrcx in task manager to bring it back into focus, this is a common issue with desktop applications on windows especially when using a multi monitor setup, the json is updated based on a timer when you resize or close the window as to save on write spam.

**Comment by ladyc0libri** [comment] 2024-01-18 18:42
I'm not sure if this is the reason, but smth doesn't allow me to run a windows update. I got 0x80070643 error
Microsoft has confirmed a massive error 0x80070643 (can be designated as ERROR_INSTALL_FAILURE) when installing the KB5034441 update on Windows 10 and Windows 11 version 21H2; the error does not appear to appear in newer versions of the system.

![image](https://github.com/vrcx-team/VRCX/assets/157014916/cc40a74c-04ef-4da9-aeda-7013d1e965b1)

btw in cmd it says No damage to the component store was detected.
The operation was completed successfully.

**Comment by ladyc0libri** [comment] 2024-01-19 20:15
i did, got the Error: 1 Invalid function.
(Dism /Online /Cleanup-Image /StartComponentCleanup)
Dism /Online /Cleanup-Image /RestoreHealth this one was ok

**Comment by Myrkie** [comment] 2024-01-19 20:52
attempt to run vrcx, again if its not we cannot help you any further as the issue is caused by your system.

**Closed** 2024-02-01 14:00 UTC
Labels: bug
