### ISSUE TITLE
[Bug] Auto accept invite requests broken

### ISSUE THREAD

**Issue by BlackWolfWoof** [vrcx-team/VRCX#889] opened 2024-08-30 11:55 UTC
**Describe the bug**
When "Auto Accept Invite Requests" is enabled and set to "VRCX Favorites" (in my case "VIP", "Known"), it does not auto accept any invites of any member of such groups.
I noticed this after moving my configuration to a new PC a moth ago. It has been broken since then and i am guessing it might be because of that. No clue how i'd fix that though.

**To Reproduce**
1. Create a group
2. Add a friend to a group
3. Enable "Auto Accept Invite Requests" and set it to VRCX favorites
4. Set VRCX Favorites groups
5. Join a vrchat world on online/ask to join and ask a friend in the group to request an invite for you.
6. Your friend will now wait for your VRCX to accept the invite which it does not.
(Not tested on a new installation of VRCX without import, but i can do it if required)

**Expected behavior**
It auto accepts the invite of the friend

**Screenshots**
N/A

**What version you are running**
VRCX 2024.07.29

**Comment by Nekromateion** [comment] 2024-08-30 12:47
Hey,

after looking into it, the issue isn't specific to the auto accept invite requests feature.
I'm looking into how to solve the issue currently and it *should* be fixed in the next Nightly update.

**Closed** 2024-09-01 08:38 UTC
Labels: bug
