### ISSUE TITLE
[Bug] When "Show PC Uptime" is enabled, steady high CPU usage

### ISSUE THREAD

**Issue by Gamersven** [vrcx-team/VRCX#743] opened 2024-03-05 23:30 UTC
**Describe the bug**
If i turn on the option "Show PC Uptime" in "Wrist Overlay" i get a constant CPU Usage of about 5%.
This even if no SteamVR or VRChat is running.
Disabling this Option fixes it and the CPU usage is down again.

**To Reproduce**
If i turn this option on or off i get instant high/low CPU usage.
When i give my sqlite db to a friend, his CPU did not Spike, even when activating this option.
So i guess this has to do something with my PC.

**Expected behavior**
Dont spike my CPU usage like that.

**Screenshots**
<img width="893" alt="Taskmgr_Off" src="https://github.com/vrcx-team/VRCX/assets/35612832/f3fcd253-6645-412b-b1ad-85e0f6bbcbc9">
<img width="911" alt="Taskmgr_On" src="https://github.com/vrcx-team/VRCX/assets/35612832/088b231d-60b1-4f68-8327-af413769069b">

**What version you are running**
Currently running 2024-03-04T23.20 (but had issues before that a long time)
AMD R7 5800X
Windows 10 (German)

Is there additional Information i can provide to assist you in finding this bug?

**Comment by Natsumi-sama** [comment] 2024-03-15 15:17
Give the latest nightly build a try, I couldn't replicate this issue but if it was the cause it should be fixed now.

**Closed by Natsumi-sama** 2024-03-15 15:17 UTC
Labels: bug, done

**Comment by Gamersven** [comment] 2024-03-16 14:43
Hi,

thank you for trying to fix my issue.
Sadly the new nightly version is completely broken, as in it does not start anymore after the update.

The only log i got with this version is this:

2024-03-16 15:34:11.6148 [INFO ] VRCX                 - VRCX Nightly 2024-03-15T15.08-0b64416
 Starting... 
2024-03-16 15:34:11.6643 [DEBUG] VRCX.ProcessMonitor  - Added process vrchat to process monitor. 
2024-03-16 15:34:11.6643 [DEBUG] VRCX.ProcessMonitor  - Added process vrserver to process monitor. 
2024-03-16 15:34:12.6880 [INFO ] VRCX.WorldDBManager  - Listening for requests on http://127.0.0.1:22500/ 

and it closes/crashes itself shortly after starting VRCX.

is there anything further i could do to help you?

**Comment by Natsumi-sama** [comment] 2024-03-16 14:44
Does the nightly version before this one work? can you check if your anti virus is affecting anything?

**Comment by Gamersven** [comment] 2024-03-16 16:06
Actually yeah, that was the version i was running prior.

I got it working now.
After Cloning the Repo and setting up VS and some bruteforce trying to get it trying to launch through there i got an error message that pointed me to the possible right? solution i guess.

It crashed right there:
        public static void ApplyVrJavascriptBindings(IJavascriptObjectRepository repository)
        {
            repository.NameConverter = null;
--->     repository.Register("AppApiVr", AppApiVr.Instance);
        }

I dont have the exact error message anymore and i cant recreate it but it said like my System.Diagnostics.PerformanceCounter.dll could be corrupted or something like that. 
Still dont know how this could happen but these steps possibly fixed it:
https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/manually-rebuild-performance-counters

<img width="867" alt="Taskmgr_xgUMB9sMwA" src="https://github.com/vrcx-team/VRCX/assets/35612832/43859167-7c94-4108-8ca7-b1d63ffb4f77">
Newest Nightly without my CPU issue and with Uptime enabled.



Im sorry for your troubles.
Thank you very much <3
Greetings from Germany

**Comment by Natsumi-sama** [comment] 2024-03-16 16:18
Thanks for looking deep into it makes my life much easier, interesting.... I guess I'll add ~~Try Catch~~ error handling to the performance counter stuff.
