### ISSUE TITLE
[Feature Request] export/import block list, sharing btw different accounts

### ISSUE THREAD

**Issue by plautus2** [vrcx-team/VRCX#965] opened 2024-10-31 06:30 UTC
It is needed. I am tired of having to block every single user again when  I create a new account to have a fresh start.

I dont care if u think it is needed or not, I NEED IT!

So please add it!

**Comment by Natsumi-sama** [comment] 2024-10-31 06:32
What makes your request more important than everyone else's.

**Comment by Myrkie** [comment] 2024-10-31 06:43
as said previously in [this issue](https://github.com/vrcx-team/VRCX/issues/927#issuecomment-2383413963) VRChat is not a fan of bulk moderation's like this, this can result in VRChat applying moderation's on users such as account bans as they are not very fond of automated moderation's. obviously that would be a terrible idea to implement for the above reasons.

**Comment by plautus2** [comment] 2024-10-31 06:56
how about trying it out???

**Comment by Myrkie** [comment] 2024-10-31 06:57
> how about trying it out???

__VRChat is not a fan of bulk moderation's like this__

**Comment by OctoFloofy** [comment] 2024-10-31 06:58
The better question is why do you need new accounts so often apparently that it is that important.

**Comment by plautus2** [comment] 2024-10-31 06:59
> > how about trying it out???
> 
> **VRChat is not a fan of bulk moderation's like this**

find a way around to make it work

**Comment by Myrkie** [comment] 2024-10-31 07:02
> find a way around to make it work

if you wish to have this feature so badly, consider pull requesting it we are not inclined to add it for the above reasons.

**Comment by DubyaDude** [comment] 2024-10-31 07:05
1. This is a duplicate of https://github.com/vrcx-team/VRCX/issues/927
2. Please be respectful to the developers. We make and maintain this app out of volunteer work. No one user's voice can outshout the others. The developers have the free will to decide what features are more important at the current time.
**If you're really that desperate for this feature**. consider implementing it yourself, or find someone to pay to put their time into implementing your feature into the project.
3. As stated before, bulk moderation is very frowned upon. Not saying this feature is impossible, but unlikely to happen without some sort of consequence.

**Closed** 2024-10-31 07:09 UTC
Labels: feature
